// lib/compliance/kra.ts
// KRA-ready transaction export utilities.
// Used by the /api/compliance/kra-export route handler.

export type ExportPeriod = "monthly" | "quarterly" | "annual";
export type ExportFormat = "csv" | "pdf";

export interface KraTransaction {
  date: string; // ISO date string
  tripId: string;
  description: string;
  grossAmount: number; // KES, before commission
  commissionAmount: number; // KES, deducted by platform
  netAmount: number; // KES, credited to rider wallet
  mpesaRef?: string;
  paymentMethod: "MPESA" | "CASH" | "WALLET";
  status: "COMPLETED" | "REFUNDED" | "DISPUTED";
}

export interface KraExportOptions {
  riderId: string;
  period: ExportPeriod;
  year: number;
  month?: number; // 1-12, required for monthly
  quarter?: number; // 1-4, required for quarterly
  format: ExportFormat;
}

/** Date range for the requested KRA period */
export function periodToDateRange(opts: Pick<KraExportOptions, "period" | "year" | "month" | "quarter">): {
  from: Date;
  to: Date;
} {
  const { period, year, month, quarter } = opts;

  if (period === "monthly") {
    if (!month) throw new Error("month is required for monthly period");
    const from = new Date(year, month - 1, 1);
    const to = new Date(year, month, 0, 23, 59, 59, 999);
    return { from, to };
  }

  if (period === "quarterly") {
    if (!quarter) throw new Error("quarter is required for quarterly period");
    const startMonth = (quarter - 1) * 3;
    const from = new Date(year, startMonth, 1);
    const to = new Date(year, startMonth + 3, 0, 23, 59, 59, 999);
    return { from, to };
  }

  // Annual
  const from = new Date(year, 0, 1);
  const to = new Date(year, 11, 31, 23, 59, 59, 999);
  return { from, to };
}

/** Format KES amounts to 2 d.p. string */
export function formatKES(amount: number): string {
  return amount.toFixed(2);
}

/** Build CSV string from transactions */
export function buildCsv(transactions: KraTransaction[], riderName: string, pin?: string): string {
  const headers = [
    "Date",
    "Trip ID",
    "Description",
    "Gross Amount (KES)",
    "Platform Commission (KES)",
    "Net Earnings (KES)",
    "M-Pesa Ref",
    "Payment Method",
    "Status",
  ].join(",");

  const rows = transactions.map((tx) =>
    [
      tx.date,
      tx.tripId,
      `"${tx.description}"`,
      formatKES(tx.grossAmount),
      formatKES(tx.commissionAmount),
      formatKES(tx.netAmount),
      tx.mpesaRef ?? "",
      tx.paymentMethod,
      tx.status,
    ].join(",")
  );

  const totals = transactions.reduce(
    (acc, tx) => {
      acc.gross += tx.grossAmount;
      acc.commission += tx.commissionAmount;
      acc.net += tx.netAmount;
      return acc;
    },
    { gross: 0, commission: 0, net: 0 }
  );

  const summary = [
    "",
    `"Rider: ${riderName}"`,
    pin ? `"KRA PIN: ${pin}"` : `"KRA PIN: (not provided)"`,
    `"Total Gross,${formatKES(totals.gross)}"`,
    `"Total Commission,${formatKES(totals.commission)}"`,
    `"Total Net,${formatKES(totals.net)}"`,
    `"Generated by Pikii on ${new Date().toISOString()}"`,
    `"This document is for tax reference only. Consult a certified tax professional."`,
  ].join("\n");

  return [headers, ...rows, summary].join("\n");
}

/** Summarize totals for a set of transactions */
export function summarizeTransactions(transactions: KraTransaction[]) {
  return transactions.reduce(
    (acc, tx) => ({
      totalGross: acc.totalGross + tx.grossAmount,
      totalCommission: acc.totalCommission + tx.commissionAmount,
      totalNet: acc.totalNet + tx.netAmount,
      count: acc.count + 1,
    }),
    { totalGross: 0, totalCommission: 0, totalNet: 0, count: 0 }
  );
}
